### ISSUE TITLE
W2L2 section 3: invisible chargers

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#110]
**Build version**
1142-d257ddf0c

**Description**
In W2L2_Section 3, at 20%, 2 drillers appear, and almost instantly disappear.
Before they completely disappear, you can notice that 2 chargers appear and fall on the same location than the drillers.
The 2 chargers will still have their word displayed, and will still deal damage to the player, but they are invisible.

**Steps to reproduce**
Difficulty level 3
- start W2L2
- reach section 3
- reach 20 %
- notice at that moment, 2 drillers appear, and almost instantly disolve
- before their complete disolve, 2 chargers will appear on the same location than the drillers
- the chargers will still be there, invisible.

**Video**
https://user-images.githubusercontent.com/25956631/166951935-2cee0992-5943-4f1d-9dc4-f5c546d0a8d7.mp4

**Comment by HugoBourbon** [comment]
This was linked to wrong spawners index.
It has been fixed, tested and pushed.
