### ISSUE TITLE
Road frequently disappear under avatar's feet in W3L2 section 1

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#116]
**Build version**
1147-bec05d4db

**Description**
Road frequently disappears under avatar's feet in W3L2 section 1.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/168025590-0f748a53-401c-4f00-8aa2-dc710b609b59.png)

**Comment by LeanderSimonart** [comment]
This happens because in this scene we have a very small roadpiece while we are expecting the same length for every piece, so this needs to be fixed in the hda
![image](https://user-images.githubusercontent.com/33334408/168228445-a1237fc1-69db-4d8a-bf46-bcd894157b92.png)

**Comment by InnoAnca** [comment]
road splitting redo with fewer pieces : all with same length
