### ISSUE TITLE
W3L2 mini boss has no decor. Monoliths are missing

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#117]
**Build version**
1147-bec05d4db

**Description**
W3L2 mini boss has no decor. Monoliths are missing.
P_monolith_door_mbLOD
p_monolith_door_mb3LOD

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/168027447-f787056e-5ad0-45d3-9c32-cb3a0f898ab1.png)

**Comment by HugoBourbon** [comment]
This was linked to an error in the Monolith's shader.
The models are already well placed in the world3 scenes.
