### ISSUE TITLE
shield fx is partially broken

### ISSUE THREAD

**Issue by LeanderSimonart** [cguillaume44/Outshine-Issues#119]
the shield vfx is partially broken, see the second included picture, for now I disable the spawners that create those particles see the first picture
![image](https://user-images.githubusercontent.com/33334408/168237100-08457ab9-f42c-4642-b99b-b2f3e3445787.png)
![image](https://user-images.githubusercontent.com/33334408/168238312-8b8db845-e016-4210-92a4-0d0d0e476130.png)

**Comment by HugoBourbon** [comment]
This was due to unintentional removal of shadergraph assets.
We put them back and it fixed the shield
