### ISSUE TITLE
W2L3 - section 3 - 90% : road is dissapearing

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#125]
**Build version**
1162-d78d15df9

**Description**
W2L3 - section 3 - 90%: road is disappearing.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/168826982-35f0d149-cd37-4087-8176-dd286f1e4655.png)

**Comment by LeanderSimonart** [comment]
because of the sharp curve at the end of the road the ordering is not correct with a z distance check, screen shows the correct order
![image](https://user-images.githubusercontent.com/33334408/168829546-cd3d7096-8b18-4706-a91f-96cc2e218855.png)
