### ISSUE TITLE
W1L2 - section 2  - 60% : unstating issue

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#127]
**Build version**
1162-d78d15df9

**Description**
In W1L2 section 2 - 60%, 4 enemies spawn and unstage instantly.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/168831344-6a3596dd-af85-4c8c-8b9d-c34c50ea7f24.png)

**Comment by HugoBourbon** [comment]
This was linked to wrong row index in enemy spawners.
It has been fixed and tested.
