### ISSUE TITLE
Credits: road disappears frequently

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#128]
**Build version**
1170-033e17636

**Description**
Credits: road disappears frequently:
- 10%
- 20%
- 30%
- 40%
- 50%
- 60%
- 70%
- 80%
- 90%

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/169052397-4891039a-1fee-4c1c-aba3-834a47e73710.png)

**Comment by LeanderSimonart** [comment]
This was an issue with the vertex colors
