### ISSUE TITLE
W3L2 - section 2 - 5% : Enemies spawn and instantly unstage

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#129]
**Build version**
1171-94efc72af

**Description**
In W3L2 - section 2 - 5%, enemies spawn and instantly unstage.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/169065870-730af21a-881d-4d3a-95f5-bdf0b6da1d48.png)

**Comment by HugoBourbon** [comment]
This was linked to wrong row index in the enemy spawners.
It has been fixed and tested.
