### ISSUE TITLE
W3L3 - section 3: Road frequently disappears

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#130]
**Build version**
1171-94efc72af

**Description**
W3L3 - section 3: road frequently disappears:
- 10%
- 17%
- 22%
- 27%
- 33%
- 38%
- etc

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/169070117-685dc347-efec-4830-b616-e4c5ecf846a3.png)

**Comment by LeanderSimonart** [comment]
@InnoAnca This is caused by the small road pieces at the end of the road ( we had this issue before ) its piece 16 and 17
![image](https://user-images.githubusercontent.com/33334408/169109991-f715a089-456f-4475-9728-22592dff9111.png)
