### ISSUE TITLE
The last section of the missile ability bar is never filled

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#134]
**Build version**
1176-e8dfa5cb2

**Description**
Missile ability bar: the last section of this bar is never filled.

The player always begins a level with 2/5 filled bar. If he doesn't use any of the missiles, at the end of section 3, he will reach 4/5 filled bar.

**Expected**
Bar could be divided into 4 sections instead of 5?

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/169492756-44d4b0bf-3137-4578-8612-ba23f58a45fa.png)

**Comment by HugoBourbon** [comment]
The number of missile charges depend of the difficulty selected.
On easiest and easy difficulty, you start with 3 charges. As you gain an extra charge per section completed, you can entirely fill your missile gauge at the thirs section of a level on easiest or easy difficulty.
