### ISSUE TITLE
Road frequently disappears during final boss level

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#135]
**Build version**
1176-e8dfa5cb2

**Description**
Road frequently disappears during final boss level.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/169556496-b4f0e575-bfc2-4eb8-beaa-46a3553acb4b.png)

**Comment by InnoAnca** [comment]
FYI, it's just because track resolution V was too low
