### ISSUE TITLE
Interface sounds are not played

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#136]
**Build version**
1177-90b817ef0

**Description**
Interface sounds are not played in the pause menu during gameplay

**Steps to reproduce**
- check that interface volume slider is not set at 0
- navigate/type words in the main menu options
- notice interface sounds can be heard
- start a level
- open the pause menu (ESC), and type letters in menus
- notice no interface sound is played

**NOTE**
In the pause menu, if you type "resume", you won't hear anything durignthe typing, but you'll hear the interface FX being fastly played as soon as the focus is back in-game.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/170042664-054cc58d-34a7-4dd7-8b33-dd9c4c17ad71.png)

**Comment by HugoBourbon** [comment]
The UpdateMode of the menu SFXs needed to be switched to "UnscaledGameTime" to be played during the game pause.
