### ISSUE TITLE
Pop corn enemies do not affect player

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#139]
**Build version**
1177-90b817ef0

**Description**
Pop corn enemies do not affect player. No damage, no speed up, no effect has been noticed.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/170962224-ff934ded-0df5-4b0a-a49d-8d0308eba4fe.png)

**Comment by HugoBourbon** [comment]
The popcorn enemies effect is just to decrease the colourcombo gauge by 1 (black color on the screenshot).
If there are more than 4 popcorns on the player, then a damage is applied.
