### ISSUE TITLE
Audio options are not applied on the "welcome" screen

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#16]
Description:
Audio options are not applied on the "welcome" screen. The audio options are applied only after reaching the Main Menu.

1. Boot the title
2. Go to Options
3. Go to Audio
4. Set all volumes to a lower level
5. Close the title
6. Boot the title
7. Wait on the "welcome" screen for the music to start
8. Notice the volume
9. Press any key to reach the Main Menu
10. Notice that the audio options are not applied while on the "welcome" screen

Expected behavior
Audio options should apply in all menus/screens.

Video: https://user-images.githubusercontent.com/101404099/158143400-7db5b9c9-02df-4af0-863a-d6aa2ca6c2b4.mp4

Misc:
 - Version: 1054
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8243475/Player.log)

**Comment by cguillaume44** [comment]
@MaxDaniels @LeanderSimonart  can we do something about that (without too much work) with the current save system?
