### ISSUE TITLE
[W1L4 - Section #1 - 0%] The user can use letters of words that are not visible yet on the map

### ISSUE THREAD

**Issue by georgeserbanozn** [cguillaume44/Outshine-Issues#18]
Description:
The user can use letters of words that are not visible yet on the map. It can be observed that, the user will not be able to type the other visible words, until he does not press the "backspace" button to clear the letters.

1. Boot the title
2. Start the level "W1L4  SECTION 1 - 0%"
3. Press multiple keyboard button keys untill you guess a letter from a word that cannot be seen yet
4. Attempt to complete the visible words
5. Notice that the user is not able complete the visible words if he started another word that can not be seen yet

Video: 
https://user-images.githubusercontent.com/101404425/158153082-b0b28bf5-45ea-437f-8ac5-10e520c8a367.mp4

Misc:
- Version: 1054
- Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8243721/Player.log)

**Comment by HugoBourbon** [comment]
I set a ByDistance activation to the "Obstacle" prefabs.
It's now working fine (and reload correctly too if the avatar die).
