### ISSUE TITLE
An error is generated if any level is started on the "Hard" difficulty

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#21]
Description:
When starting any level on "Hard" difficulty it can be noticed that an error is generated.

1. Boot the title
2. Select any level
3. Set the difficulty to "Hard"
4. Press the "Play" button
5. Notice that an error if generated

Expected behavior
No errors should be generated when starting levels on "Hard" difficulty.

Video: https://user-images.githubusercontent.com/101404099/158172264-7fc8d132-dde2-4613-bba0-5853dbf47625.mp4

Misc:
 - Version: 1054
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8244756/Player.log)

**Comment by LeanderSimonart** [comment]
This should happen with all modifiers and this the same underlying issue as in #29
