### ISSUE TITLE
The title crashed once during the "W1L5 - Section #1" while typing words at high speed

### ISSUE THREAD

**Issue by georgeserbanozn** [cguillaume44/Outshine-Issues#25]
Description:
The title crashed during the "W1L5 - Section # 1" while typing words at high speed.  Please note that this issue occured just once and we were unable to reproduce it.

1. Boot the title
2. Start the "W1L5 - Section # 1"
3. Type words at a high speed
4. Note that the title crashes

Misc:
- Version: 1054
- Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8245554/Player.log)
- Crash log: [crash.zip](https://github.com/cguillaume44/Outshine-Issues/files/8245620/crash.zip)

**Comment by MaxDaniels** [comment]
It seems to be related to this "> BANK has no pool with P_FX_Hud_ComboX5".

I'll will update the bank content tool to force a list of object to be present in all contents.
