### ISSUE TITLE
The "Narrow Sight" modifier is not working properly

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#38]
Description:
The "Narrow Sight" modifier is not working properly. There are some cases where words of the enemies on other rows (lanes) can be seen.
Please note that this issue occurs for hovering spawner enemies.

1. Boot the title
2. Select W2L2
3. Enable "Narrow Sight" modifier
4. Start the level
5. Progress through the level
6. Notice that words from different rows (lanes) can be seen without being on that row (lane)

Expected behavior:
Only words from the row (lane) on which the player is should be visible.

Video 1: https://user-images.githubusercontent.com/101404099/158326648-d8531954-ea00-40c4-a937-58bf6c3ad961.mp4
Video 2: https://user-images.githubusercontent.com/101404099/158326750-f6fdb3dd-5b8b-4cc2-a5df-8af155fe2d49.mp4
Video 3: https://user-images.githubusercontent.com/101404099/158326826-b77064c2-bb16-4408-8222-5d687af8cd4d.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8251006/Player.log)

**Comment by MaxDaniels** [comment]
This bug could be side-effects of previous errors in the scenario.
