### ISSUE TITLE
Typing accuracy is not 100% while playing with the "Perfect Typing" modifier enabled

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#40]
Description:
Typing accuracy is not 100% while playing with the "Perfect Typing" modifier enabled. Since the modifier kills the player's character if a mistype occurs the typing accuracy should be 100% at checkpoints/end of the level.

1. Boot the title
2. Start any level with the "Perfect Typing" modifier
3. Reach first checkpoint while typing words 
4. Notice that the word accuracy is not 100% even though no word was mistyped

Expected behavior
The typing accuracy should be 100% at checkpoints/end of the level since no words are mistyped.

Screenshots: 
![Screenshot_1](https://user-images.githubusercontent.com/101404099/158332996-2757065b-36d5-4b69-a9ef-fee80a0624f5.png)
![Screenshot_2](https://user-images.githubusercontent.com/101404099/158333012-423b31bc-8a8f-4b9d-8906-2d1ad0faab90.png)

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8251277/Player.log)

**Comment by MaxDaniels** [comment]
I don't think the % computation is broken, but the errors in logs could have break something ( enemy, words, ... )

**Comment by MaxDaniels** [comment]
@HugoBourbon : confirm ?

**Comment by cguillaume44** [comment]
The accuracy isn't resetted if you die, hence the non-100% stat.
==> By design
