### ISSUE TITLE
The explosion effect when enemies are destroyed can get corrupted

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#42]
Description:
The explosion effect when enemies are destroyed can get corrupted. This issue can occur on any level and the reproduction rate is not consistent (2/20 - 10%). 

1. Boot the title
2. Start any level (preferably a more advanced one)
3. Destroy enemies by typing words 
4. Notice that the explosion effect when enemies are destroyed can get corrupted and remain on screen for a longer period of time

Expected behavior
No graphical corruptions should be present in game.

Video 1: https://user-images.githubusercontent.com/101404099/158337149-cd116360-cbcb-43af-a1f9-d0b0e704dd24.mp4
Video 2: https://user-images.githubusercontent.com/101404099/158337554-59793db2-2490-42db-9cab-a77d35e319ca.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8251462/Player.log)

**Comment by cguillaume44** [comment]
Duplicate #6
