### ISSUE TITLE
After enemies despawn their words can remain displayed on screen

### ISSUE THREAD

**Issue by georgeserbanozn** [cguillaume44/Outshine-Issues#44]
Description:
Please note that even though the enemy disappeared, if its word remained displayed it can still be typed. 
The reproduction rate for this issue is very low (1/20 - 5%).

1. Boot the title
2. Select W2L2
3. Start the level
4. Progress through the level
5. Notice that there are some enemies that despawn and their words can remain displayed on the screen

Expected behavior:
The words of the enemies should not remain displayed after their visual assets disappear. 

Video: https://user-images.githubusercontent.com/101404425/158342390-fd84b6a4-255b-4ecc-ab72-11f36ea55ce9.mp4

Misc:
- Version: 1057-da37f841b
- Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8251006/Player.log)

**Comment by LeanderSimonart** [comment]
At first sight this seems to be an issue related to the modifiers
