### ISSUE TITLE
Some enemies can spawn and disappear immediately without having time to destroy them

### ISSUE THREAD

**Issue by georgeserbanozn** [cguillaume44/Outshine-Issues#45]
Description:
Some enemies can spawn and disappear immediately without having time to destroy them.  This issue seems to have a higher rate of reproduction in W2L2 Section 3.
The reproduction rate for this issue is very low (1/20 - 5%).

1. Boot the title
2. Select any level
3. Start the level
4. Progress through the level
5. Notice that there are some enemies that disappear immediately without having time to destroy them

Expected behavior:
The enemies should not disappear immediately after they are spawned.

Video: https://user-images.githubusercontent.com/101404425/158343441-c390dda1-3650-40ea-9816-ce45058efd17.mp4

Misc:
- Version: 1057-da37f841b
- Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8251006/Player.log)

**Comment by cguillaume44** [comment]
Unfortunately it's by design and would be expensive to fix
