### ISSUE TITLE
The score multiplier for the "No Checkpoint" modifier is too small compared to other modifiers

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#48]
Description:
When comparing the "No Checkpoint" modifier with other much more forgiving modifiers it can be noticed that the score multiplier for the "No Checkpoint" modifier is too small. 

1. Boot the title
2. Select any level
3. Read the description of all modifiers and notice their score multiplier 
4. Notice that the score multiplier for the "No Checkpoint" modifier is too small compared to other modifiers

Expected behavior:
Due to the difficulty the "No Checkpoint" modifier adds to the game its score multiplier should be higher than 0.10.

Screenshot: ![Screenshot](https://user-images.githubusercontent.com/101404099/158349162-60c35167-23c9-4e9d-bf5d-65c956043ba0.png)

Misc:
 - Version: 1057-da37f841b

**Comment by HugoBourbon** [comment]
This value doesn't need to be changed, as it is easily achievable.
But other values were slightly changed.
