### ISSUE TITLE
Flying enemies will not perform their shoot action after retrying the level

### ISSUE THREAD

**Issue by georgeserbanozn** [cguillaume44/Outshine-Issues#50]
Description:
Flying enemies will not perform their shoot action after retrying the level. Please note that an error is also occured when the flying enemy attempts to shoot.

1. Boot the title
2. Select W2L3 level
3. Start the level
4. Press the "Retry" button
5. Take a look at the flying enemies
6. Note that the flying enemies will not perform the shoot action after retrying the level

Expected behavior:
The enemies should perform their action normaly after retrying the level.

Video: https://user-images.githubusercontent.com/101404425/158355166-abfcbdcc-c2f5-4516-9c7a-dc76f6d23800.mp4

Misc:
- Version: 1057-da37f841b
- Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8252192/Player.log)

**Comment by MaxDaniels** [comment]
Fixed ( same bug as #55 with enemy weapons ).
