### ISSUE TITLE
Words from enemy towers that spawn other enemies are not displayed if the "Disappearance of Words" modifier is enabled

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#53]
Description:
If the "Disappearance of Words" modifier is enabled the words for enemy towers that spawn other enemies (the ones that are located on the edge of the road) are not displayed at all.

1. Boot the title
2. Start a level that has enemy towers (W2L4 for example) with the "Disappearance of Words" modifier enabled 
3. Progress through the level
4. Notice that the words from enemy towers are not displayed at all

Expected behavior
Words should be visible for a brief period of time before starting to fade while having the "Disappearance of Words" modifier enabled .

Video: https://user-images.githubusercontent.com/101404099/158372257-401715ba-afa8-4383-8ea7-dcba68a6ee7d.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8252961/Player.log)

**Comment by MaxDaniels** [comment]
@HugoBourbon : design choice or bug ?

**Comment by MaxDaniels** [comment]
This bug is due to height difference between player and the mortar ( the weak-point renderer is disabled ).
The usage of this modifier just emphasis the visual aspect of the problem.
