### ISSUE TITLE
Chinese, Japanese and Korean languages are not functional

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#56]
Description:
Chinese, Japanese and Korean languages are not functional. All characters are a pink placeholder and some are completely missing. Also some errors are generated when selecting the specified languages.

1. Boot the title
2. Go to "Options"
3. Change the language to Chinese, Japanese or Korean
4. Notice that the languages are not functional and errors are generated.

Expected behavior
All available languages should be functional.

Video: https://user-images.githubusercontent.com/101404099/158385642-fe945477-e462-42f6-ade9-38de4cbd06a4.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8253571/Player.log)

**Comment by cguillaume44** [comment]
Those languages are disabled in retail build
