### ISSUE TITLE
The health of the W4_boss is not going down after damaging the boss

### ISSUE THREAD

**Issue by AndreiIscu** [cguillaume44/Outshine-Issues#57]
Description:
The health of the W4_boss is not going down after damaging the boss. Please note that this is only visual issue. The boss can be defeated even though the health bar remains full throughout the fight.

1. Boot the title
2. Start W4_Boss level
3. Damage the boss by typing words
4. Notice that the boss' health bar is not going down

Expected behavior:
The boss' health bar should go down after damaging the boss.

Video: https://user-images.githubusercontent.com/101404099/158393523-3fff7d0d-013a-455d-9ff2-7868dcc58756.mp4

Misc:
 - Version: 1057-da37f841b
 - Logs: [Player.log](https://github.com/cguillaume44/Outshine-Issues/files/8253938/Player.log)

**Comment by MaxDaniels** [comment]
Fixed.
