### ISSUE TITLE
Screen is blinking/flashing

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#61]
**Build version**
1082-0573761cf

**Description**
The image is blinking/flashing in some levels.
Here, this bug has been spotted in W2L1 - section 1.

**Steps to reproduce**
start the W2L1, and you'll notice the issue immediately at the start of the level.

**Details**
Linked to quality settings. Flashes occurs from very low quality to high quality. Only very high quality does not cause any flashes.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/159014075-4515b99b-7c66-46d1-a69e-6900664bbc6e.png)

**Comment by LeanderSimonart** [comment]
Would you have a video showcasing the issue? cuz its hard to see blinking/flashing on a still image
