### ISSUE TITLE
Cinematic not playing on Integrated graphics

### ISSUE THREAD

**Issue by LeanderSimonart** [cguillaume44/Outshine-Issues#63]
From the demo from steamFest we got feedback from several players where the cinematic would not play and therefore break the game.
They were all using integrated graphics.

**Comment by cguillaume44** [comment]
Transcoded the cinematics today as an attempt to fix this

**Comment by cguillaume44** [comment]
Must be tested on Integrated graphics computer @guillaumeDerudder
