### ISSUE TITLE
W2L4 : Invalid Giant trigger parameters @45%

### ISSUE THREAD

**Issue by MaxDaniels** [cguillaume44/Outshine-Issues#66]
![image](https://user-images.githubusercontent.com/28396445/159527720-70566028-fc8c-4c1d-96a0-f8d6ba9a2bf1.png)

**Comment by MaxDaniels** [comment]
![image](https://user-images.githubusercontent.com/28396445/159527768-8b71e8b7-4d28-435b-8cb7-0e144c5507a7.png)

**Comment by MaxDaniels** [comment]
Unstagging distance must be set > 47%.

*** Temporary set to 58% ***

**Comment by HugoBourbon** [comment]
I've set missing default values for the ZO_EnemiesSequence_Giant prefab
