### ISSUE TITLE
Boss 2 camera far plane issue

### ISSUE THREAD

**Issue by cguillaume44** [cguillaume44/Outshine-Issues#68]
Already fixed in the past this issue came back in build : 

Depending on the location of the camera the bkg buildings disappear due to the camera far plane occlusion

![image](https://user-images.githubusercontent.com/51667183/159656579-8fb58ad2-af60-4cb7-91a3-2295538110c9.png)

**Comment by HugoBourbon** [comment]
Something is forcing the FarClipPlane of the Cam9_Boss2 to 1500 at the beginning of the fight (it is set to 8000 by default).
The only component that I know that can do that is the SplineTriggerCamera, but there is none in the w2_boss gameplay scene.
