### ISSUE TITLE
W2L2 section3 : miniboss 2

### ISSUE THREAD

**Issue by stourmecedric** [cguillaume44/Outshine-Issues#69]
red crystals FX on burned have color issue:

![image](https://user-images.githubusercontent.com/15229368/159689000-04a63380-eaa9-405e-a60f-834140a4c6b3.png)

miniboss curently spawn "P_RoadDestroyedElement0"...
![image](https://user-images.githubusercontent.com/15229368/159689181-14e06d34-f410-499a-8285-a4794a1af6cc.png)
...but should spawn "P_RoadDestroyedElement0_W2".

**Comment by MaxDaniels** [comment]
![image](https://user-images.githubusercontent.com/28396445/159710561-ab4b8c5f-3cac-4258-99e6-f8c478586813.png)

P_Enemy_14_Laser should be updated with correct prefabs.

**Comment by MaxDaniels** [comment]
Element 0 -> world 1, 
Element 1 -> world 2, 
etc...
