### ISSUE TITLE
Chinese and Japanese: Drillers and Launchers sometimes do not have companion word

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#74]
**Build version**
asian_language_support 1-1da0b70d4

**Description**
Drillers and launchers sometimes do no have heir companion word displayed in Chinese and Japanese.

**Steps to reproduce**
The easiest way to reproduce that is playing W1L2 - section 1, and reach 28.0 %. Press then F5 to immobilize your character on that position.
Don't forget to set language as Chinese or Japanese.

- notice most time, enemies have their companion word displayed
- defeat some enemies
- notice sometimes, drillers and launchers do not have their companion word displayed.

**Screenshots**
Chinese:
![image](https://user-images.githubusercontent.com/25956631/161541756-b9695863-8a83-408a-91ec-3675d7244c79.png)

Japanese:
![image](https://user-images.githubusercontent.com/25956631/161541781-34c8124d-a891-4811-a68c-e99a526429ec.png)

**Comment by LeanderSimonart** [comment]
This happens when we are missing a symbol in the font, so the font is broken code-wise it is working
