### ISSUE TITLE
The Miniboss3 is not reseted correctly after a death

### ISSUE THREAD

**Issue by HugoBourbon** [cguillaume44/Outshine-Issues#79]
**Describe the bug**
If you die during the W1L3 level, the MiniBoss3 weakpoints are not reseted correctly.

**To Reproduce**
1. Play the level W1L3
2. Die before encountering the Miniboss3
3. Try to beat the Miniboss3
4. Some weakpoints don't appear on screen and cannot be typed

**Misc:**
 - Version: Build 1105-ac3834113

**Comment by guillaumeDerudder** [comment]
Indeed, this occurs well.
- play W1L3
- die before encountering the miniboss
- you will notice that the pales of the boss will not display weakpoint
- impossible to defeat the miniboss, player is stuck

![image](https://user-images.githubusercontent.com/25956631/162179608-633866c6-36d1-49c7-b38c-cbab0d5ab32c.png)

**Comment by MaxDaniels** [comment]
Some fixes have been done about other bugs, but can't reproduce this one.

**Comment by guillaumeDerudder** [comment]
Can't reproduce in latest build (tested on 1114).
