### ISSUE TITLE
Miniboss 5 lasers makes the screen blink black

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#84]
**Version**
1107-5d494660d

**Description**
When the miniboss 5 shoots its lasers, it makes the screen "blink black".

**Steps to reproduce**
- start a level where you have to fight miniboss 5
- during the fight, wait that it shoots lasers at you
- notice when the laser reachers the player/camera, the screen blinks

**Video**
https://user-images.githubusercontent.com/25956631/162746744-0560dcea-9a38-4acb-802e-61b32089fee0.mp4

**Comment by LeanderSimonart** [comment]
This is not always reproducible as I am not triggering it with the provided steps, could a log be included or more precise repro steps?

**Comment by guillaumeDerudder** [comment]
Looks like this is only occuring on some hardware.
Render capture has to be done.

**Comment by guillaumeDerudder** [comment]
After render capture, it has been noticed the blue gives an infinity value in graphics debugger.
The issue is coming from the crystals.
Screenshots:
![image](https://user-images.githubusercontent.com/25956631/164211567-0ec1683f-71db-4032-8453-129f7fe00ae5.png)
![image](https://user-images.githubusercontent.com/25956631/164211616-2aaa44d5-2f85-49e6-91c2-ebf6744a649b.png)
![image](https://user-images.githubusercontent.com/25956631/164211679-58b4a90c-24c4-4007-beb8-5d07026b3028.png)

infos: https://docs.unity3d.com/Packages/com.unity.render-pipelines.high-definition@10.1/manual/Post-Processing-Propagating-NaNs.html

**Comment by LeanderSimonart** [comment]
This should be fixed with the new crystals that cedric made.
