### ISSUE TITLE
Missiles shoot FX is missing

### ISSUE THREAD

**Issue by guillaumeDerudder** [cguillaume44/Outshine-Issues#93]
**Build version**
1122-32bc35cf4

**Description**
Missiles shoot FX is missing.
here, you can see a screenshot of the miniboss 5, but it occurs with every missiles shot by any enemy in the game.

**Screenshot**
![image](https://user-images.githubusercontent.com/25956631/164418949-1db6e1e2-30e0-4e3c-9899-f15a5a65891b.png)

**Comment by LeanderSimonart** [comment]
This particular issue ( pink box ) does not occur anymore as there is no missile fx being fired anymore.
But we would like to have a dedicated effect for the missiles to draw the attention of the player to the missile
